name: My First Workflow
on: push
jobs:
  first_job: 
    runs-on: ubuntu-latest
    steps:
      - name: Welcome message
        run: echo "My first github workflow"

      - name: List files
        run: ls

      - name: Read file
        run: cat Dockerfile